language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
#  - openjdk8
#  missing javafx, so a no-build.
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport &&
    sbt ++$TRAVIS_SCALA_VERSION coverageAggregate &&
    sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
