language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
  - openjdk8
script:
  - sudo apt-get install openjfx
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport &&
    sbt ++$TRAVIS_SCALA_VERSION coverageAggregate &&
    sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
